color_schemes = {
    'dark - nw': {
        'lines':    {'bg': '#3f5e77', },
        'tile':     {'bg': '#2e3b48',   'fg': '#aebde2'},
        'target':   {'bg': '#5cc679',   'fg': 'black'},
        'player':   {'bg': '#2fc2e0',   'fg': 'black'},
        'trail':    {'bg': '#3f7ba3',   'fg': '#182028'},
        'chaser':   {'bg': '#e069b6',   'fg': 'black'},
        'nommer':   {'bg': '#2899e0',   'fg': 'black'},
        'runner':   {'bg': '#5cc679',   'fg': 'black'},
        },
    'vanilla': {  # c8d2bd
        'lines':    {'bg': '#ededed', },
        'tile':     {'bg': 'white',     'fg': 'black'},
        'target':   {'bg': '#ffd402',   'fg': 'black'},
        'player':   {'bg': '#54c3ff',   'fg': 'black'},
        'trail':    {'bg': '#fcfaf7',   'fg': 'black'},
        'chaser':   {'bg': '#d86cb8',   'fg': 'black'},
        'nommer':   {'bg': '#88c942',   'fg': 'black'},
        'runner':   {'bg': '#ffd402',   'fg': 'black'},
        },
    'sheep': {
        'lines':    {'bg': '#78ce27', },
        'tile':     {'bg': '#8ce537',   'fg': '#006400'},
        'target':   {'bg': '#32cd32',   'fg': 'black'},
        'player':   {'bg': 'white',     'fg': 'black'},
        'trail':    {'bg': '#adff2f',   'fg': '#006400'},
        'chaser':   {'bg': '#ff4500',   'fg': 'black'},
        'nommer':   {'bg': 'white',     'fg': 'black'},
        'runner':   {'bg': 'white',     'fg': 'black'},
        },
    'strawberry - nw': {
        'lines':    {'bg': '#ffb5b5', },
        'tile':     {'bg': '#fdeded',   'fg': 'black'},
        'target':   {'bg': '#99de00',   'fg': 'black'},
        'player':   {'bg': '#ff606e',   'fg': 'black'},
        'trail':    {'bg': '#fd939c',   'fg': 'black'},
        'chaser':   {'bg': '#ea56e9',   'fg': 'black'},
        'nommer':   {'bg': '#00ebd3',   'fg': 'black'},
        'runner':   {'bg': '#ffb5b5',   'fg': 'black'},
        },
    'baby blue - nw': {
        'lines':    {'bg': '#84b0e5', },
        'tile':     {'bg': '#bee9fa',   'fg': 'black'},
        'target':   {'bg': '#63beff',   'fg': 'black'},
        'player':   {'bg': '#00bfff',   'fg': 'black'},
        'trail':    {'bg': '#7faae1',   'fg': 'black'},
        'chaser':   {'bg': '#ee82ee',   'fg': 'black'},
        'nommer':   {'bg': '#7fff00',   'fg': 'black'},
        'runner':   {'bg': '#63beff',   'fg': 'black'},
        },
    'matrix': {
        'lines':    {'bg': '#1c1c1c', },
        'tile':     {'bg': 'black',     'fg': 'darkGrey'},
        'target':   {'bg': 'black',     'fg': 'greenYellow'},
        'player':   {'bg': 'limeGreen', 'fg': 'black'},
        'trail':    {'bg': 'darkGreen', 'fg': 'black'},
        'chaser':   {'bg': 'red',       'fg': 'black'},
        'nommer':   {'bg': 'limeGreen', 'fg': 'black'},
        'runner':   {'bg': 'limeGreen', 'fg': 'black'},
        },
    'pac-man': {
        'lines':    {'bg': 'darkBlue', },
        'tile':     {'bg': 'black',     'fg': 'yellow'},
        'target':   {'bg': 'cornSilk',  'fg': 'black'},
        'player':   {'bg': 'yellow',    'fg': 'black'},
        'trail':    {'bg': '#1c1c1c',   'fg': 'seashell'},
        'chaser':   {'bg': 'red',       'fg': 'black'},
        'nommer':   {'bg': 'cyan',      'fg': 'black'},
        'runner':   {'bg': 'yellow',    'fg': 'black'},
    },
}
