color_schemes = {
    'default': {
        'lines':    {'bg': 'whiteSmoke', },
        'tile':     {'bg': 'white',         'fg': 'black'},
        'target':   {'bg': 'gold',          'fg': 'black'},
        'player':   {'bg': 'deepSkyBlue',   'fg': 'black'},
        'trail':    {'bg': 'lightCyan',     'fg': 'black'},
        'chaser':   {'bg': 'hotPink',       'fg': 'black'},
        'nommer':   {'bg': 'yellowGreen',   'fg': 'black'},
        'runner':   {'bg': 'gold',          'fg': 'black'},
    },
    'sheep :>': {
        'lines':    {'bg': '#77ef02', },
        'tile':     {'bg': 'lawnGreen',     'fg': 'darkGreen'},
        'target':   {'bg': 'limeGreen',     'fg': 'black'},
        'player':   {'bg': 'white',         'fg': 'black'},
        'trail':    {'bg': 'greenYellow',   'fg': 'darkGreen'},
        'chaser':   {'bg': 'orangeRed',     'fg': 'black'},
        'nommer':   {'bg': 'white',         'fg': 'black'},
        'runner':   {'bg': 'white',         'fg': 'black'},
    },
    'dark - NW': {
        'lines':    {'bg': '#3f5e77', },
        'tile':     {'bg': '#2e3b48',       'fg': '#c3cfef'},
        'target':   {'bg': '#5cc679',       'fg': 'black'},
        'player':   {'bg': '#55d1ff',       'fg': 'black'},
        'trail':    {'bg': '#54a0d0',       'fg': 'black'},
        'chaser':   {'bg': '#dc68b3',       'fg': 'black'},
        'nommer':   {'bg': '#2492c6',       'fg': 'black'},
        'runner':   {'bg': '#2492c6',       'fg': 'black'},
    },
    'matrix': {
        'lines':    {'bg': '#1c1c1c', },
        'tile':     {'bg': 'black',         'fg': 'darkGrey'},
        'target':   {'bg': 'black',         'fg': 'greenYellow'},
        'player':   {'bg': 'limeGreen',     'fg': 'black'},
        'trail':    {'bg': 'darkGreen',     'fg': 'black'},
        'chaser':   {'bg': 'red',           'fg': 'black'},
        'nommer':   {'bg': 'red',           'fg': 'black'},
        'runner':   {'bg': 'red',           'fg': 'black'},
    },
    'pac-man': {
        'lines':    {'bg': 'darkBlue', },
        'tile':     {'bg': 'black',         'fg': 'yellow'},
        'target':   {'bg': 'cornSilk',      'fg': 'black'},
        'player':   {'bg': 'yellow',        'fg': 'black'},
        'trail':    {'bg': '#1c1c1c',       'fg': 'seashell'},
        'chaser':   {'bg': 'red',           'fg': 'black'},
        'nommer':   {'bg': 'cyan',          'fg': 'black'},
        'runner':   {'bg': 'yellow',        'fg': 'black'},
    },
    'strawberry - NW': {
        'lines':    {'bg': '#ffb5b5', },
        'tile':     {'bg': '#fdeded',       'fg': 'black'},
        'target':   {'bg': '#99de00',       'fg': 'black'},
        'player':   {'bg': '#ff707c',       'fg': 'black'},
        'trail':    {'bg': '#fd939c',       'fg': 'black'},
        'chaser':   {'bg': '#ea56e9',       'fg': 'black'},
        'nommer':   {'bg': '#00ebd3',       'fg': 'black'},
        'runner':   {'bg': '#00ebd3',       'fg': 'black'},
    },
    'baby blue - NW': {
        'lines':    {'bg': '#84b0e5', },
        'tile':     {'bg': '#bee9fa',       'fg': 'black'},
        'target':   {'bg': '#63beff',       'fg': 'black'},
        'player':   {'bg': '#00bfff',       'fg': 'black'},
        'trail':    {'bg': '#7faae1',       'fg': 'black'},
        'chaser':   {'bg': '#ee82ee',       'fg': 'black'},
        'nommer':   {'bg': '#7fff00',       'fg': 'black'},
        'runner':   {'bg': '#7fff00',       'fg': 'black'},
    },
}
